/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package succinct.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FileHandle implements org.apache.thrift.TBase<FileHandle, FileHandle._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FileHandle");

  private static final org.apache.thrift.protocol.TField RESPONSIBLE_CLIENT_FIELD_DESC = new org.apache.thrift.protocol.TField("responsibleClient", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("fileName", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FileHandleStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FileHandleTupleSchemeFactory());
  }

  public String responsibleClient; // required
  public String fileName; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONSIBLE_CLIENT((short)1, "responsibleClient"),
    FILE_NAME((short)2, "fileName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSIBLE_CLIENT
          return RESPONSIBLE_CLIENT;
        case 2: // FILE_NAME
          return FILE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSIBLE_CLIENT, new org.apache.thrift.meta_data.FieldMetaData("responsibleClient", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE_NAME, new org.apache.thrift.meta_data.FieldMetaData("fileName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FileHandle.class, metaDataMap);
  }

  public FileHandle() {
  }

  public FileHandle(
    String responsibleClient,
    String fileName)
  {
    this();
    this.responsibleClient = responsibleClient;
    this.fileName = fileName;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FileHandle(FileHandle other) {
    if (other.isSetResponsibleClient()) {
      this.responsibleClient = other.responsibleClient;
    }
    if (other.isSetFileName()) {
      this.fileName = other.fileName;
    }
  }

  public FileHandle deepCopy() {
    return new FileHandle(this);
  }

  @Override
  public void clear() {
    this.responsibleClient = null;
    this.fileName = null;
  }

  public String getResponsibleClient() {
    return this.responsibleClient;
  }

  public FileHandle setResponsibleClient(String responsibleClient) {
    this.responsibleClient = responsibleClient;
    return this;
  }

  public void unsetResponsibleClient() {
    this.responsibleClient = null;
  }

  /** Returns true if field responsibleClient is set (has been assigned a value) and false otherwise */
  public boolean isSetResponsibleClient() {
    return this.responsibleClient != null;
  }

  public void setResponsibleClientIsSet(boolean value) {
    if (!value) {
      this.responsibleClient = null;
    }
  }

  public String getFileName() {
    return this.fileName;
  }

  public FileHandle setFileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

  public void unsetFileName() {
    this.fileName = null;
  }

  /** Returns true if field fileName is set (has been assigned a value) and false otherwise */
  public boolean isSetFileName() {
    return this.fileName != null;
  }

  public void setFileNameIsSet(boolean value) {
    if (!value) {
      this.fileName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESPONSIBLE_CLIENT:
      if (value == null) {
        unsetResponsibleClient();
      } else {
        setResponsibleClient((String)value);
      }
      break;

    case FILE_NAME:
      if (value == null) {
        unsetFileName();
      } else {
        setFileName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSIBLE_CLIENT:
      return getResponsibleClient();

    case FILE_NAME:
      return getFileName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESPONSIBLE_CLIENT:
      return isSetResponsibleClient();
    case FILE_NAME:
      return isSetFileName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FileHandle)
      return this.equals((FileHandle)that);
    return false;
  }

  public boolean equals(FileHandle that) {
    if (that == null)
      return false;

    boolean this_present_responsibleClient = true && this.isSetResponsibleClient();
    boolean that_present_responsibleClient = true && that.isSetResponsibleClient();
    if (this_present_responsibleClient || that_present_responsibleClient) {
      if (!(this_present_responsibleClient && that_present_responsibleClient))
        return false;
      if (!this.responsibleClient.equals(that.responsibleClient))
        return false;
    }

    boolean this_present_fileName = true && this.isSetFileName();
    boolean that_present_fileName = true && that.isSetFileName();
    if (this_present_fileName || that_present_fileName) {
      if (!(this_present_fileName && that_present_fileName))
        return false;
      if (!this.fileName.equals(that.fileName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FileHandle other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FileHandle typedOther = (FileHandle)other;

    lastComparison = Boolean.valueOf(isSetResponsibleClient()).compareTo(typedOther.isSetResponsibleClient());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponsibleClient()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responsibleClient, typedOther.responsibleClient);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFileName()).compareTo(typedOther.isSetFileName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFileName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fileName, typedOther.fileName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FileHandle(");
    boolean first = true;

    sb.append("responsibleClient:");
    if (this.responsibleClient == null) {
      sb.append("null");
    } else {
      sb.append(this.responsibleClient);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("fileName:");
    if (this.fileName == null) {
      sb.append("null");
    } else {
      sb.append(this.fileName);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (responsibleClient == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'responsibleClient' was not present! Struct: " + toString());
    }
    if (fileName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'fileName' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FileHandleStandardSchemeFactory implements SchemeFactory {
    public FileHandleStandardScheme getScheme() {
      return new FileHandleStandardScheme();
    }
  }

  private static class FileHandleStandardScheme extends StandardScheme<FileHandle> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FileHandle struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSIBLE_CLIENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.responsibleClient = iprot.readString();
              struct.setResponsibleClientIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.fileName = iprot.readString();
              struct.setFileNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FileHandle struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.responsibleClient != null) {
        oprot.writeFieldBegin(RESPONSIBLE_CLIENT_FIELD_DESC);
        oprot.writeString(struct.responsibleClient);
        oprot.writeFieldEnd();
      }
      if (struct.fileName != null) {
        oprot.writeFieldBegin(FILE_NAME_FIELD_DESC);
        oprot.writeString(struct.fileName);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FileHandleTupleSchemeFactory implements SchemeFactory {
    public FileHandleTupleScheme getScheme() {
      return new FileHandleTupleScheme();
    }
  }

  private static class FileHandleTupleScheme extends TupleScheme<FileHandle> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FileHandle struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.responsibleClient);
      oprot.writeString(struct.fileName);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FileHandle struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.responsibleClient = iprot.readString();
      struct.setResponsibleClientIsSet(true);
      struct.fileName = iprot.readString();
      struct.setFileNameIsSet(true);
    }
  }

}

